version: '3.9'
services:
  database:
    image: mysql
    container_name: vidalcode
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'abc'
      MYSQL_DATABASE: 'bd_vidalcode'
    ports:
      - 3308:3306